run:
    issue-exit-code: 1
    timeout: 3m

skip-dirs:
    - assets # megalinter results+fixes

issues:
    include:
      - EXC0002
      - EXC0011
      - EXC0012
      - EXC0013
      - EXC0014
      - EXC0015

linters-settings:
    errcheck:
        check-type-assertions: true
        check-blank: true
        ignore: fmt:.*
        disable-default-exclusions: false
    gocritic:
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - unnamedResult
    govet:
        check-shadowing: true
        enable-all: false
        disable-all: false
        enable:
            - fieldalignment
    nolintlint:
        require-explanation: true
        require-specific: true
    gocyclo:
        # minimal code complexity to report, 30 by default (but we recommend 10-20)
        min-complexity: 15
    depguard:
        list-type: blacklist
        include-go-root: true

linters:
    disable-all: true
    enable:
        - bodyclose
        - unused
        - depguard
        - dogsled
        - dupl
        - errcheck
        - exportloopref
        - exhaustive
        - goconst
        - gocritic
        - gofmt
        - goimports
        - gocyclo
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nolintlint
        - nakedret
        - prealloc
        - predeclared
        - revive
        - staticcheck
        - stylecheck
        - thelper
        - tparallel
        - typecheck
        - unconvert
        - unparam
        - whitespace
        - wsl
        - megacheck
        - contextcheck
